# used for creating binder environment 
name: pypsa-agora-h2
channels:
  - conda-forge
dependencies:
  - python >=3.11,<3.12.0a0
  - pypsa==0.28
  - ipython
  - ipykernel==6.25.0
  - numpy
  - pandas==2.1 # >=1.4.3
  - coincbc