# used for creating binder environment 
name: pypsa-h2-training
channels:
  - bioconda
  - conda-forge
dependencies:
  - git
  - ipykernel==6.25.0
  - ipython==9.4.0
  - jupyterlab==4.4.5
  - nbstripout==0.8.1
  - numpy==1.26.4
  - pandas==2.3.1
  - pypsa==0.35.1
  - python==3.12.11
